(function () {
  const $ = (s, root = document) => root.querySelector(s);
  const app = $('#app');
  const state = { lang: getLanguage(), session:null, profile:null, domains:[], bookmarks:new Set(), lastFocus:null };
  const t = key => window.I18N[state.lang]?.[key] || window.I18N.en[key] || key;
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const localized = value => value?.[state.lang] || value?.ko || value?.en || '—';
  const date = value => value ? new Intl.DateTimeFormat(state.lang, { dateStyle:'medium' }).format(new Date(`${value}`.slice(0,10) + 'T00:00:00')) : '—';

  function getLanguage() { const saved=localStorage.getItem('akashic_lang'); const guessed=navigator.language.slice(0,2); return ['ko','en','ja'].includes(saved) ? saved : (['ko','en','ja'].includes(guessed) ? guessed : 'en'); }
  function setLanguage(lang) { state.lang=lang; localStorage.setItem('akashic_lang',lang); document.documentElement.lang=lang; document.body.dataset.lang=lang; route(); }
  function toast(message) { const el=$('#toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),3000); }
  function langPicker() { return `<label class="sr-only" for="lang">${t('language')}</label><select id="lang" class="lang-select" data-action="language"><option value="ko" ${state.lang==='ko'?'selected':''}>KO</option><option value="en" ${state.lang==='en'?'selected':''}>EN</option><option value="ja" ${state.lang==='ja'?'selected':''}>JA</option></select>`; }
  function button(label, href, type='gold') { return `<a class="button ${type}" href="${href}">${label}</a>`; }
  function authShell(content) { return `<main class="gateway"><div class="gateway-top">${langPicker()}</div><section class="terminal">${content}</section><p class="gateway-note">ARCHIVE PROTOCOL · OPEN KNOWLEDGE · VERIFIED SOURCES</p></main>`; }
  function warning() { app.innerHTML=authShell(`<div class="mark">◈</div><p class="eyebrow">UNIVERSAL MEMORY ARCHIVE</p><h1>${t('archive')}</h1><p class="lead">${t('tagline')}</p><div class="oath"><strong>${t('warning')}</strong><p>${t('warningBody')}</p></div><div class="gateway-actions">${button(t('login'),'#/login')}${button(t('signup'),'#/signup','red')}</div><a class="text-link" href="#/about">${t('why')}</a>`); }
  function authForm(kind) {
    const signup=kind==='signup', reset=kind==='reset', update=kind==='update';
    const title=signup?t('signup'):(reset||update?t('reset'):t('login'));
    app.innerHTML=authShell(`<a href="#/welcome" class="back">← ${t('cancel')}</a><p class="eyebrow">ARCHIVE ACCESS TERMINAL</p><h1>${title}</h1><form id="auth-form" data-kind="${kind}"><div class="field"><label for="email">${t('email')}</label><input id="email" name="email" type="email" autocomplete="email" ${update?'hidden':'required'}></div>${!reset?`<div class="field"><label for="password">${t('password')}</label><input id="password" name="password" type="password" minlength="8" autocomplete="${signup?'new-password':'current-password'}" required></div>`:''}${signup?`<div class="field"><label for="confirm">${t('confirm')}</label><input id="confirm" name="confirm" type="password" minlength="8" required></div><div class="field"><label for="displayName">${t('displayName')}</label><input id="displayName" name="displayName" maxlength="20" required></div><label class="check"><input type="checkbox" name="consent" required> ${t('consent')}</label>`:''}<p class="form-message" role="alert"></p><button class="button gold" type="submit">${t('submit')}</button></form>${kind==='login'?`<div class="form-links"><a href="#/reset">${t('reset')}</a><a href="#/signup">${t('signup')}</a></div>`:''}`);
  }
  function setup() { app.innerHTML=authShell(`<div class="mark">◇</div><p class="eyebrow">CONFIGURATION</p><h1>${t('setup')}</h1><p class="lead">${t('setupBody')}</p><ol class="setup-list"><li><code>sql/schema.sql</code> 실행</li><li><code>sql/rls.sql</code> 실행</li><li><code>sql/seed.sql</code> 실행</li><li><code>config.example.js</code>를 <code>config.js</code>로 복사 후 공개 anon 키 입력</li><li><code>index.html</code>에서 <code>config.js</code>를 <code>supabase.js</code> 앞에 로드</li></ol><a class="button gold" href="README.md">${t('setupAction')}</a>`); }
  function shell(content, crumb=t('home')) {
    const p=state.profile || {};
    app.innerHTML=`<header class="site-header"><div class="classification"><span class="pulse">● LIVE ARCHIVE</span><span>CLEARANCE ${['','Α','Β','Γ','Δ','Θ'][p.level||2]}</span><span>${esc(p.keeper_code||'KEEPER')}</span>${langPicker()}<button class="icon-button mobile-menu" data-action="menu" aria-label="${t('menu')}">☰</button><button class="text-button" data-action="logout">${t('logout')}</button></div><div class="brand"><a href="#/"><span>◈</span> ${t('archive')}</a><small>${t('tagline')}</small></div><div class="crumb"><span>${t('breadcrumb')}:</span> ${crumb}</div></header><div class="layout"><main id="content" tabindex="-1">${content}</main>${sidebar()}</div><footer>◈ ${t('warning')} · PRESERVE CONTEXT · CITE YOUR SOURCES</footer><div class="drawer-scrim" data-action="menu"></div>`;
  }
  function sidebar() { return `<aside class="sidebar" aria-label="Archive navigation"><nav><a href="#/">⌂ ${t('explore')}</a><a href="#/bookmarks">☆ ${t('bookmarks')}</a><a href="#/mine">⌁ ${t('mine')}</a><a href="#/new">＋ ${t('newRecord')}</a>${state.profile?.is_admin?`<a href="#/moderation">⚖ ${t('moderation')}</a>`:''}<a href="#/about">? ${t('about')}</a></nav><section class="side-block"><h2>${t('recent')}</h2><div id="recent-list" class="recent-list"><span class="muted">${t('emptyRecent')}</span></div></section><section class="principles"><span>${t('connected')}</span><span>${t('perspective')}</span><span>${t('evidence')}</span></section><label class="motion"><input type="checkbox" data-action="motion" ${localStorage.getItem('akashic_motion')==='reduce'?'checked':''}> ${t('motion')}</label></aside>`; }
  function skeleton() { return `<div class="skeleton heading"></div><div class="card-grid">${'<div class="skeleton card"></div>'.repeat(4)}</div>`; }
  async function home() { shell(`<section class="hero"><p class="eyebrow">THE LIVING INDEX</p><h1>${t('allKnowledge')}</h1><p>${t('tagline')}</p><form class="search" id="search-form"><label class="sr-only" for="q">${t('search')}</label><input id="q" placeholder="${t('searchHint')}"><button aria-label="${t('search')}">⌕</button></form><div id="stats" class="stats"><span>—<small>${t('totalRecords')}</small></span><span>—<small>${t('todayRecords')}</small></span><span>—<small>${t('contributors')}</small></span></div></section><section><div class="section-title"><div><p class="eyebrow">KNOWLEDGE CONSTELLATIONS</p><h2>${t('topics')}</h2></div></div><div id="domain-grid" class="domain-grid">${'<div class="skeleton domain"></div>'.repeat(6)}</div></section>`); await Promise.all([loadDomains(),loadStats(),loadRecent()]); }
  async function loadDomains() { try { state.domains=await ArchiveAPI.domains(); $('#domain-grid').innerHTML=state.domains.map((d,i)=>`<a class="domain-card" href="#/d/${esc(d.id)}"><span class="domain-number">${String(i+1).padStart(2,'0')}</span><span class="domain-icon">${esc(d.icon||'◇')}</span><h3>${esc(localized(d.name))}</h3><p>${esc(localized(d.description))}</p><span class="arrow">→</span></a>`).join(''); } catch(e){ showInlineError('#domain-grid',e); } }
  async function loadStats(){ try { const x=await ArchiveAPI.counts(); $('#stats').innerHTML=`<span>${x.record_count}<small>${t('totalRecords')}</small></span><span>${x.today_count}<small>${t('todayRecords')}</small></span><span>${x.keeper_count}<small>${t('contributors')}</small></span>`; } catch(_){} }
  async function loadRecent(){ try { const records=await ArchiveAPI.recent(); const el=$('#recent-list'); if(el&&records.length)el.innerHTML=records.map(r=>`<a href="#/r/${r.record_code}">${esc(localized(r.title))}</a>`).join(''); } catch(_){} }
  async function domainPage(id) { shell(skeleton(), `${t('home')} » ${esc(id)}`); try { const domain=(await ArchiveAPI.domains()).find(x=>x.id===id); if(!domain) return notFound(); const cats=await ArchiveAPI.categories(id); const records=await ArchiveAPI.records({domain:id}); shell(`<header class="page-intro"><span class="domain-icon large">${esc(domain.icon)}</span><p class="eyebrow">${esc(domain.id)}</p><h1>${esc(localized(domain.name))}</h1><p>${esc(localized(domain.description))}</p></header><div class="category-strip">${cats.map(c=>`<a href="#/d/${id}/c/${c.id}">${esc(localized(c.name))}<span>→</span></a>`).join('')}</div>${recordSection(records,t('home'),{domain:id})}`,`${t('home')} » ${esc(localized(domain.name))}`); loadRecent(); } catch(e){ errorPage(e); } }
  function recordSection(records,title=t('home'),filters=null) { const more=filters&&records.length===20?`<button class="button gold load-more" data-action="load-more" data-page="1" data-filters="${encodeURIComponent(JSON.stringify(filters))}">${t('loadMore')}</button>`:'';return `<section class="records"><div class="section-title"><h2>${title}</h2><label>${t('sort')} <select data-action="sort"><option value="created">${t('newest')}</option><option value="eventDesc">${t('eventNewest')}</option><option value="eventAsc">${t('eventOldest')}</option><option value="title">${t('titleSort')}</option><option value="levelDesc">${t('levelHigh')}</option></select></label></div><div class="record-grid">${records.length?records.map(recordCard).join(''):empty()}</div>${more}</section>`; }
  function recordCard(r) { const locked=r.content_available===false && r.level>(state.profile?.level||0); return `<article class="record-card"><div class="record-meta"><span>${esc(r.record_code)}</span><span>LEVEL-${r.level}</span><button class="bookmark ${state.bookmarks.has(r.id)?'active':''}" data-action="bookmark" data-id="${r.id}" aria-label="${t('bookmarks')}">${state.bookmarks.has(r.id)?'★':'☆'}</button></div><p class="path">${esc(localized(r.domain_name))} / ${esc(localized(r.category_name))} ${r.status==='under_review'?`<strong class="review-badge">${t('underReview')}</strong>`:''}</p><h3>${esc(localized(r.title))}</h3><p class="summary ${locked?'redacted':''}">${locked?'████████ █████ ███████':esc(localized(r.summary))}</p><div class="tags">${(r.tags||[]).slice(0,5).map(tag=>`<span>#${esc(tag)}</span>`).join('')}</div><div class="record-foot"><span>${date(r.event_date)}</span><span>${esc(r.keeper_code||'KEEPER')}</span></div><a class="stretched" href="#/r/${esc(r.record_code)}">${t('details')} →</a></article>`; }
  async function listPage(filters,crumb) { shell(skeleton(),crumb); try { const records=await ArchiveAPI.records(filters); shell(recordSection(records,crumb,filters),crumb); loadRecent(); } catch(e){errorPage(e);} }
  async function bookmarksPage(){ shell(skeleton(),t('bookmarks')); try { const records=await ArchiveAPI.bookmarks(); shell(recordSection(records,t('bookmarks')),t('bookmarks')); }catch(e){errorPage(e);} }
  async function minePage(){shell(skeleton(),t('mine'));try{const records=await ArchiveAPI.myRecords(state.session.user.id);const cards=records.length?records.map(mineRecordCard).join(''):empty();shell(`<section class="records"><div class="section-title"><h1>${t('mine')}</h1></div><div class="record-grid">${cards}</div></section>`,t('mine'));}catch(e){errorPage(e);}}
  function mineRecordCard(r){const deleted=!!r.deleted_at;return `<article class="record-card mine-card"><div class="record-meta"><span>${esc(r.record_code)}</span><strong class="status-${deleted?'deleted':r.status}">${deleted?'DELETED':String(r.status).toUpperCase()}</strong></div><h3>${esc(localized(r.title))}</h3><p class="summary">${esc(localized(r.summary))}</p><div class="record-foot"><span>${date(r.event_date)}</span><span>LEVEL-${r.level}</span></div><div class="mine-actions">${!deleted?`<a class="button gold" href="#/edit/${esc(r.record_code)}">${t('edit')}</a>`:''}${!deleted?`<button class="button red" data-action="delete" data-id="${r.id}">${t('delete')}</button>`:''}${!deleted&&r.status!=='hidden'?`<a class="button gold" href="#/r/${esc(r.record_code)}">${t('details')}</a>`:''}</div></article>`;}
  function empty(){ return `<div class="empty"><span>◇</span><h3>NO RECORDS ON FILE</h3><p>${t('noRecords')}</p></div>`; }
  async function detail(code){
    shell(skeleton(),code);
    try{
      const r=await ArchiveAPI.record(code);if(!r)return notFound();
      await ArchiveAPI.view(state.session.user.id,r.id);shell(recordSection([r]),code);
      const content=r.content_available?`<div class="document-content">${esc(localized(r.content)).replace(/\n/g,'<br>')}</div>`:`<div class="clearance"><span>████████</span><p>${t('insufficient')}</p></div>`;
      const owner=r.author_id===state.session.user.id;
      const modal=document.createElement('div');modal.className='modal-layer';
      modal.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="record-title" tabindex="-1"><div class="modal-actions"><button data-action="bookmark" data-id="${r.id}" aria-label="${t('bookmarks')}">${state.bookmarks.has(r.id)?'★':'☆'}</button>${owner?`<a class="modal-icon" href="#/edit/${esc(r.record_code)}" aria-label="${t('edit')}">✎</a><button data-action="delete" data-id="${r.id}" aria-label="${t('delete')}">⌫</button>`:`<button data-action="report" data-record="${r.id}" aria-label="${t('report')}">⚑</button>`}<button data-action="close" aria-label="${t('close')}">×</button></div><p class="eyebrow">CLASSIFIED DOCUMENT · ${esc(r.record_code)}</p><h1 id="record-title">${esc(localized(r.title))}</h1><dl><div><dt>${t('domain')}</dt><dd>${esc(localized(r.domain_name))} › ${esc(localized(r.category_name))}</dd></div><div><dt>${t('eventDate')}</dt><dd>${date(r.event_date)}</dd></div><div><dt>${t('createdAt')}</dt><dd>${date(r.created_at)}</dd></div><div><dt>${t('author')}</dt><dd>${esc(r.keeper_code)}</dd></div><div><dt>${t('source')}</dt><dd><a href="${esc(r.source)}" target="_blank" rel="noopener noreferrer">${esc(r.source)}</a></dd></div></dl>${content}<div class="tags">${(r.tags||[]).map(x=>`<span>#${esc(x)}</span>`).join('')}</div><section class="related"><h2>${t('related')}</h2><div id="related-records"><div class="skeleton heading"></div></div></section></div>`;
      document.body.append(modal);document.body.classList.add('modal-open');state.lastFocus=document.activeElement;$('.modal',modal).focus();
      loadRelated(r.id);
    }catch(e){errorPage(e);}
  }
  async function loadRelated(recordId){try{const records=await ArchiveAPI.related(recordId);const el=$('#related-records');if(!el)return;if(!records.length){$('.related')?.remove();return;}el.innerHTML=records.map(r=>`<a class="related-item" href="#/r/${esc(r.record_code)}"><span>${esc(r.record_code)}</span><strong>${esc(localized(r.title))}</strong><small>${esc(localized(r.domain_name))} · SCORE ${r.score}</small></a>`).join('');}catch(_){$('.related')?.remove();}}
  async function editor(code=null){
    if(!state.domains.length)state.domains=await ArchiveAPI.domains();
    const record=code?await ArchiveAPI.ownRecord(code,state.session.user.id):null;
    const opts=state.domains.map(d=>`<option value="${d.id}" ${record?.domain_id===d.id?'selected':''}>${esc(localized(d.name))}</option>`).join('');
    const languageFields=['ko','en','ja'].map((lang,index)=>`<fieldset class="translation-panel ${index?'hidden':''}" data-lang-panel="${lang}"><legend>${lang.toUpperCase()}</legend><div class="field"><label for="title-${lang}">${t('title')}</label><input id="title-${lang}" name="title_${lang}" maxlength="100" value="${esc(record?.title?.[lang]||'')}" ${lang==='ko'?'required':''}></div><div class="field"><label for="summary-${lang}">${t('summary')}</label><textarea id="summary-${lang}" name="summary_${lang}" maxlength="300" ${lang==='ko'?'required':''}>${esc(record?.summary?.[lang]||'')}</textarea></div><div class="field"><label for="content-${lang}">${t('content')}</label><textarea id="content-${lang}" name="content_${lang}" rows="10" ${lang==='ko'?'required':''}>${esc(record?.content?.[lang]||'')}</textarea></div></fieldset>`).join('');
    shell(`<header class="page-intro"><p class="eyebrow">${record?'EDIT ARCHIVE ENTRY':'NEW ARCHIVE ENTRY'}</p><h1>${record?t('edit'):t('newRecord')}</h1></header><form id="record-form" class="record-form" data-id="${record?.id||''}"><div class="form-row"><div class="field"><label for="domain">${t('domain')}</label><select id="domain" name="domain_id" data-selected-category="${record?.category_id||''}" required>${opts}</select></div><div class="field"><label for="category">${t('category')}</label><select id="category" name="category_id" required></select></div></div><div class="language-tabs" role="tablist" aria-label="${t('language')}">${['ko','en','ja'].map((lang,i)=>`<button type="button" role="tab" aria-selected="${!i}" class="${!i?'active':''}" data-action="translation" data-lang="${lang}">${lang.toUpperCase()}${lang==='ko'?' · REQUIRED':''}</button>`).join('')}</div>${languageFields}<div class="form-row"><div class="field"><label for="event">${t('eventDate')}</label><input id="event" name="event_date" type="date" value="${esc(record?.event_date||'')}"></div><div class="field"><label for="level">${t('level')}</label><select id="level" name="level">${Array.from({length:state.profile.level},(_,i)=>`<option value="${i+1}" ${record?.level===i+1?'selected':''}>LEVEL-${i+1}</option>`).join('')}</select></div></div><div class="field"><label for="tags">${t('tags')}</label><input id="tags" name="tags" value="${esc((record?.tags||[]).join(', '))}" placeholder="history, science, memory" required></div><div class="field"><label for="source">${t('source')}</label><input id="source" name="source" type="url" value="${esc(record?.source||'')}" placeholder="https://" required></div><p class="form-message" role="alert"></p><div class="form-actions"><button class="button gold" type="submit">${t('save')}</button>${record?`<button class="button red" type="button" data-action="delete" data-id="${record.id}">${t('delete')}</button>`:''}</div></form>`,record?t('edit'):t('newRecord'));
    await populateCategories();
  }
  async function populateCategories(){ const d=$('#domain')?.value;if(!d)return; const cats=await ArchiveAPI.categories(d); const selected=$('#domain').dataset.selectedCategory; $('#category').innerHTML=cats.map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>${esc(localized(c.name))}</option>`).join(''); $('#domain').dataset.selectedCategory=''; }
  function reportDialog(recordId){
    const modal=document.createElement('div'); modal.className='modal-layer';
    modal.innerHTML=`<div class="modal compact" role="dialog" aria-modal="true" aria-labelledby="report-title"><div class="modal-actions"><button data-action="close-overlay" aria-label="${t('close')}">×</button></div><p class="eyebrow">RECORD INTEGRITY REPORT</p><h1 id="report-title">${t('report')}</h1><form id="report-form"><input type="hidden" name="recordId" value="${recordId}"><div class="field"><label for="reason">${t('reportReason')}</label><select id="reason" name="reason" required><option value="false_information">${t('falseInformation')}</option><option value="missing_source">${t('missingSource')}</option><option value="fiction">${t('fiction')}</option><option value="inappropriate">${t('inappropriate')}</option><option value="other">${t('other')}</option></select></div><div class="field"><label for="detail">${t('reportDetail')}</label><textarea id="detail" name="detail" maxlength="1000" rows="5"></textarea></div><p class="form-message" role="alert"></p><button class="button red" type="submit">${t('report')}</button></form></div>`;
    document.body.append(modal); document.body.classList.add('modal-open'); $('[data-action="close-overlay"]',modal).addEventListener('click',closeOverlay); $('#report-form',modal).addEventListener('submit',handleReport); modal.addEventListener('click',e=>{if(e.target===modal)closeOverlay();}); $('#reason',modal).focus();
  }
  async function moderationPage(){
    if(!state.profile?.is_admin){notFound();return;}
    shell(skeleton(),t('moderation'));
    try{
      const cases=await ArchiveAPI.moderationCases();
      const cards=cases.length?cases.map(c=>{const own=c.records?.author_id===state.session.user.id;const voted=c.moderation_votes?.some(v=>v.admin_id===state.session.user.id);return `<article class="meeting-card ${c.status}"><header><div><p class="eyebrow">CASE-${String(c.id).padStart(6,'0')}</p><h2>${esc(localized(c.records?.title))}</h2></div><span class="case-status">${c.status==='open'?t('meetingOpen'):t('meetingResolved')}</span></header><p>${esc(localized(c.records?.summary))}</p><a class="source-link" href="${esc(c.records?.source)}" target="_blank" rel="noopener noreferrer">${t('source')} ↗</a><div class="meeting-columns"><section><h3>${t('reports')} · ${c.report_count}</h3>${c.reports.map(r=>`<blockquote><strong>${t(({false_information:'falseInformation',missing_source:'missingSource',fiction:'fiction',inappropriate:'inappropriate',other:'other'})[r.reason])}</strong>${r.detail?`<p>${esc(r.detail)}</p>`:''}</blockquote>`).join('')}</section><section><h3>${t('votes')} · ${c.moderation_votes.length}/3</h3>${c.moderation_votes.map(v=>`<blockquote class="vote ${v.decision}"><strong>${v.decision==='keep'?t('keep'):t('hide')} · ${esc(v.profiles?.keeper_code)}</strong><p>${esc(v.note)}</p></blockquote>`).join('')||`<p class="muted">—</p>`}</section></div>${c.status==='open'&&!voted&&!own?`<form class="vote-form" data-case="${c.id}"><div class="field"><label for="note-${c.id}">${t('voteNote')}</label><textarea id="note-${c.id}" name="note" minlength="1" maxlength="1000" required></textarea></div><div class="vote-actions"><button class="button gold" name="decision" value="keep">${t('keep')}</button><button class="button red" name="decision" value="hide">${t('hide')}</button></div><p class="form-message" role="alert"></p></form>`:own&&c.status==='open'?`<p class="notice">${t('cannotVoteOwn')}</p>`:''}${c.status==='resolved'?`<p class="resolution">${c.decision==='keep'?t('keep'):t('hide')}</p>`:''}</article>`;}).join(''):empty();
      shell(`<header class="page-intro"><p class="eyebrow">ARCHIVE REVIEW COUNCIL</p><h1>${t('moderation')}</h1><p>${t('reviewIntro')}</p></header><div class="meeting-list">${cards}</div>`,t('moderation'));
    }catch(e){errorPage(e);}
  }
  function about(){ const body=`<article class="about"><p class="eyebrow">A SHARED MEMORY OF THE WORLD</p><h1>${t('why')}</h1><p class="lead">${t('whyBody')}</p><div class="about-grid"><section><span>01</span><h2>${t('evidence')}</h2><p>Every public record carries a source and a clear distinction between the subject date and archive date.</p></section><section><span>02</span><h2>${t('perspective')}</h2><p>History and experience can hold multiple interpretations. Records preserve context rather than claiming a single cosmic truth.</p></section><section><span>03</span><h2>${t('connected')}</h2><p>Domains and categories are coordinates, not isolated planets. A record may connect people, places, ideas, and eras.</p></section></div></article>`; state.session?shell(body,t('about')):app.innerHTML=authShell(`<a href="#/welcome" class="back">← ${t('cancel')}</a>${body}`); }
  function errorPage(error){ console.error(error); shell(`<div class="empty error"><span>!</span><h1>ARCHIVE CONNECTION LOST</h1><p>${esc(error.message||'Unknown error')}</p><button class="button red" onclick="location.reload()">${t('retry')}</button></div>`); }
  function notFound(){ shell(`<div class="empty"><span>404</span><h1>COORDINATE NOT FOUND</h1></div>`); }
  function showInlineError(selector,e){ const el=$(selector);if(el)el.innerHTML=`<div class="empty error"><p>${esc(e.message)}</p></div>`; }

  async function route(){ document.querySelectorAll('.modal-layer').forEach(x=>x.remove());document.body.classList.remove('modal-open');document.documentElement.lang=state.lang; document.body.dataset.lang=state.lang; document.body.classList.toggle('reduce-motion',localStorage.getItem('akashic_motion')==='reduce'); const hash=location.hash||'#/welcome'; if(!window.AkashicSupabase.configured){setup();bind();return;} if(!state.session && !['#/welcome','#/login','#/signup','#/reset','#/about'].includes(hash)){location.hash='#/welcome';return;} if(hash==='#/welcome')warning(); else if(hash==='#/login')authForm('login'); else if(hash==='#/signup')authForm('signup'); else if(hash==='#/reset')authForm('reset'); else if(hash==='#/reset/update')authForm('update'); else if(hash==='#/about')about(); else if(hash==='#/')await home(); else if(hash==='#/bookmarks')await bookmarksPage(); else if(hash==='#/mine')await minePage(); else if(hash==='#/new')await editor(); else if(hash.startsWith('#/edit/'))await editor(decodeURIComponent(hash.slice(7))); else if(hash==='#/moderation')await moderationPage(); else if(hash.startsWith('#/search?')){const q=new URLSearchParams(hash.split('?')[1]).get('q');await listPage({search:q},`${t('search')} » ${esc(q)}`);} else { let m=hash.match(/^#\/d\/([^/]+)(?:\/c\/([^/]+))?$/); if(m) m[2]?await listPage({domain:m[1],category:m[2]},`${m[1]} » ${m[2]}`):await domainPage(m[1]); else {m=hash.match(/^#\/r\/(.+)$/);m?await detail(m[1]):notFound();} } bind(); }
  function bind(){ $('[data-action="language"]')?.addEventListener('change',e=>setLanguage(e.target.value)); $('[data-action="logout"]')?.addEventListener('click',()=>ArchiveAPI.signOut()); document.querySelectorAll('[data-action="menu"]').forEach(b=>b.addEventListener('click',()=>document.body.classList.toggle('drawer-open'))); $('[data-action="motion"]')?.addEventListener('change',e=>{localStorage.setItem('akashic_motion',e.target.checked?'reduce':'full');document.body.classList.toggle('reduce-motion',e.target.checked);}); $('[data-action="sort"]')?.addEventListener('change',e=>{localStorage.setItem('akashic_sort',e.target.value);route();}); $('#domain')?.addEventListener('change',populateCategories); document.querySelectorAll('[data-action="translation"]').forEach(b=>b.addEventListener('click',switchTranslation)); document.querySelectorAll('[data-action="delete"]').forEach(b=>b.addEventListener('click',handleDelete)); document.querySelectorAll('[data-action="load-more"]').forEach(b=>b.addEventListener('click',handleLoadMore)); $('#search-form')?.addEventListener('submit',e=>{e.preventDefault();const q=new FormData(e.target).get('q')||$('#q').value;if(q.trim())location.hash=`#/search?q=${encodeURIComponent(q.trim())}`;}); $('#auth-form')?.addEventListener('submit',handleAuth); $('#record-form')?.addEventListener('submit',handleRecord); document.querySelectorAll('[data-action="bookmark"]').forEach(b=>{if(!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',handleBookmark);}}); document.querySelectorAll('[data-action="close"]').forEach(b=>b.addEventListener('click',closeModal)); document.querySelectorAll('[data-action="close-overlay"]').forEach(b=>b.addEventListener('click',closeOverlay)); document.querySelectorAll('.modal-layer').forEach(layer=>layer.addEventListener('click',e=>{if(e.target===layer){document.querySelectorAll('.modal-layer').length>1?closeOverlay():closeModal();}})); document.querySelectorAll('[data-action="report"]').forEach(b=>b.addEventListener('click',e=>reportDialog(Number(e.currentTarget.dataset.record)))); $('#report-form')?.addEventListener('submit',handleReport); document.querySelectorAll('.vote-form').forEach(f=>f.addEventListener('submit',handleVote)); }
  async function handleAuth(e){e.preventDefault();const f=new FormData(e.target),kind=e.target.dataset.kind,msg=$('.form-message',e.target);try{if(kind==='login'){const {error}=await ArchiveAPI.signIn(f.get('email'),f.get('password'));if(error)throw error;location.hash='#/';}else if(kind==='signup'){if(f.get('password')!==f.get('confirm'))throw new Error(t('authFailed'));const {error}=await ArchiveAPI.signUp(f.get('email'),f.get('password'),{display_name:f.get('displayName'),lang:state.lang});if(error)throw error;msg.textContent=t('verify');e.target.reset();}else if(kind==='reset'){await ArchiveAPI.resetPassword(f.get('email'));msg.textContent=t('resetSent');}else{await ArchiveAPI.updatePassword(f.get('password'));toast(t('save'));location.hash='#/';}}catch(_){msg.textContent=t('authFailed');}}
  async function handleRecord(e){e.preventDefault();const f=new FormData(e.target),msg=$('.form-message',e.target);try{const translated=prefix=>Object.fromEntries(['ko','en','ja'].map(lang=>[lang,(f.get(`${prefix}_${lang}`)||'').trim()]).filter(([,value])=>value));const title=translated('title'),summary=translated('summary'),content=translated('content');for(const lang of ['en','ja']){const count=[title[lang],summary[lang],content[lang]].filter(Boolean).length;if(count>0&&count<3)throw new Error(t('translationHelp'));}const tags=f.get('tags').split(',').map(x=>x.trim()).filter(Boolean);if(tags.length<1||tags.length>8)throw new Error('Tags must contain 1–8 values.');const payload={author_id:state.session.user.id,domain_id:f.get('domain_id'),category_id:f.get('category_id'),title,summary,content,event_date:f.get('event_date')||null,tags,source:f.get('source'),level:Number(f.get('level'))};const id=Number(e.target.dataset.id);const saved=id?await ArchiveAPI.updateRecord(id,payload):await ArchiveAPI.createRecord(payload);location.hash=`#/r/${saved.record_code}`;}catch(err){msg.textContent=err.message;}}
  function switchTranslation(e){const lang=e.currentTarget.dataset.lang;document.querySelectorAll('[data-action="translation"]').forEach(b=>{const active=b.dataset.lang===lang;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});document.querySelectorAll('[data-lang-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.langPanel!==lang));}
  async function handleDelete(e){if(!confirm(t('confirmDelete')))return;try{await ArchiveAPI.deleteRecord(Number(e.currentTarget.dataset.id));closeOverlay();toast(t('deleted'));location.hash='#/mine';}catch(err){toast(err.message);}}
  async function handleLoadMore(e){const button=e.currentTarget,page=Number(button.dataset.page),filters=JSON.parse(decodeURIComponent(button.dataset.filters));button.disabled=true;try{const records=await ArchiveAPI.records(filters,page);const grid=$('.record-grid');grid.insertAdjacentHTML('beforeend',records.map(recordCard).join(''));grid.querySelectorAll('[data-action="bookmark"]').forEach(b=>{if(!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',handleBookmark);}});button.dataset.page=String(page+1);button.disabled=false;if(records.length<20)button.remove();}catch(err){button.disabled=false;toast(err.message);}}
  async function handleReport(e){e.preventDefault();const f=new FormData(e.target),msg=$('.form-message',e.target);try{await ArchiveAPI.report(state.session.user.id,Number(f.get('recordId')),f.get('reason'),f.get('detail')||null);toast(t('reportSent'));closeOverlay();}catch(err){msg.textContent=err.code==='23505'?t('reportSent'):err.message;}}
  async function handleVote(e){e.preventDefault();const msg=$('.form-message',e.target);try{await ArchiveAPI.moderationVote(Number(e.target.dataset.case),state.session.user.id,e.submitter.value,new FormData(e.target).get('note'));toast(t('save'));await route();}catch(err){msg.textContent=err.message;}}
  async function handleBookmark(e){e.preventDefault();e.stopPropagation();const id=Number(e.currentTarget.dataset.id),active=state.bookmarks.has(id);try{await ArchiveAPI.toggleBookmark(state.session.user.id,id,active);active?state.bookmarks.delete(id):state.bookmarks.add(id);route();}catch(err){toast(err.message);}}
  function closeOverlay(){const layers=document.querySelectorAll('.modal-layer');const modal=layers[layers.length-1];if(modal)modal.remove();if(document.querySelectorAll('.modal-layer').length===0)document.body.classList.remove('modal-open');}
  function closeModal(){closeOverlay();if(location.hash.startsWith('#/r/'))history.back();}
  document.addEventListener('keydown',e=>{const layers=document.querySelectorAll('.modal-layer');const top=layers[layers.length-1];if(e.key==='Escape'){if(layers.length>1)closeOverlay();else if(layers.length===1)closeModal();else document.body.classList.remove('drawer-open');}if(e.key==='Tab'&&top){const focusable=[...top.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length){e.preventDefault();return;}const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  window.addEventListener('hashchange',route);
  async function init(){ if(window.AkashicSupabase.configured){state.session=await ArchiveAPI.session();if(state.session){state.profile=await ArchiveAPI.profile(state.session.user.id);state.bookmarks=await ArchiveAPI.bookmarkIds();}ArchiveAPI.onAuth(async(_,session)=>{state.session=session;state.profile=session?await ArchiveAPI.profile(session.user.id):null;if(!session)location.hash='#/welcome';route();});}route(); }
  init();
}());
