window.I18N = {
  ko: {
    skip:'본문으로 건너뛰기', archive:'아카식 레코드', tagline:'사람과 세계의 모든 지식을 연결하고 보존하는 살아 있는 기록 보관소',
    warning:'지식은 소유물이 아니라 이어지는 기억입니다.', warningBody:'이곳의 기록은 역사, 과학, 예술, 인물, 장소, 아이디어와 개인의 경험을 서로 연결합니다. 근거를 밝히고, 다른 관점을 존중하며, 미래의 독자를 위해 기록해 주세요.',
    login:'로그인', signup:'기록자 등록', logout:'로그아웃', email:'이메일', password:'비밀번호', confirm:'비밀번호 확인', displayName:'표시 이름', consent:'이용 규약 및 개인정보 처리에 동의합니다', submit:'계속', cancel:'취소', reset:'비밀번호 재설정', resetSent:'해당 계정의 존재 여부와 관계없이 안내 메일이 발송됩니다.', authFailed:'인증에 실패했습니다. 입력 내용을 확인해 주세요.', verify:'메일함에서 인증 링크를 확인해 주세요.',
    explore:'탐색', home:'전체 기록', topics:'지식 영역', collections:'컬렉션', bookmarks:'북마크', mine:'내 기록', newRecord:'새 기록', settings:'설정', about:'소개', search:'기록 검색', searchHint:'제목, 요약, 태그로 찾기', breadcrumb:'현재 위치', totalRecords:'공개 기록', todayRecords:'오늘의 기록', contributors:'기록자', recent:'최근 열람', noRecords:'아직 보존된 기록이 없습니다.', retry:'다시 시도', loadMore:'더 불러오기', details:'기록 열기', source:'출처', eventDate:'대상 시점', createdAt:'기록일', author:'기록자', level:'열람 등급', tags:'태그', edit:'수정', delete:'삭제', report:'신고', save:'저장', title:'제목', summary:'요약', content:'본문', domain:'지식 영역', category:'분류', recordType:'기록 유형', language:'언어', motion:'움직임 줄이기', sort:'정렬', newest:'최근 기록순', eventNewest:'대상 시점 최신순', eventOldest:'대상 시점 오래된순', titleSort:'제목순', insufficient:'이 기록의 전문을 열람할 권한이 없습니다.', emptyRecent:'최근 열람 기록이 없습니다.', emptyBookmarks:'보관한 기록이 없습니다.', setup:'아카이브 연결 필요', setupBody:'Supabase 프로젝트를 연결하면 가입, 공유 기록, 북마크가 모든 기기에서 동기화됩니다.', setupAction:'설정 방법 보기', menu:'메뉴 열기', close:'닫기', allKnowledge:'모든 지식', connected:'연결된 지식', perspective:'여러 관점', evidence:'검증 가능한 출처', why:'아카식 레코드는 무엇인가요?', whyBody:'아카식 레코드는 세계의 사건과 생각이 흔적처럼 보존된다는 오래된 개념에서 이름을 가져왔습니다. 이 사이트는 이를 초자연적 사실로 주장하지 않습니다. 대신 누구나 검증 가능한 지식과 자신의 경험을 기록하고, 출처·시점·관계로 연결하는 공동 지식 보관소로 재해석합니다.'
  },
  en: {
    skip:'Skip to content', archive:'Akashic Records', tagline:'A living archive connecting and preserving human knowledge', warning:'Knowledge is not property, but memory passed onward.', warningBody:'Records here connect history, science, art, people, places, ideas, and lived experience. Cite evidence, respect perspectives, and write for future readers.', login:'Sign in', signup:'Become a keeper', logout:'Sign out', email:'Email', password:'Password', confirm:'Confirm password', displayName:'Display name', consent:'I agree to the terms and privacy policy', submit:'Continue', cancel:'Cancel', reset:'Reset password', resetSent:'If an account exists, an email will be sent.', authFailed:'Authentication failed. Check your credentials.', verify:'Check your inbox for the verification link.', explore:'Explore', home:'All records', topics:'Knowledge domains', collections:'Collections', bookmarks:'Bookmarks', mine:'My records', newRecord:'New record', settings:'Settings', about:'About', search:'Search records', searchHint:'Search titles, summaries, and tags', breadcrumb:'Location', totalRecords:'Public records', todayRecords:'Today', contributors:'Keepers', recent:'Recently viewed', noRecords:'No records have been preserved here yet.', retry:'Retry', loadMore:'Load more', details:'Open record', source:'Source', eventDate:'Subject date', createdAt:'Recorded', author:'Keeper', level:'Access level', tags:'Tags', edit:'Edit', delete:'Delete', report:'Report', save:'Save', title:'Title', summary:'Summary', content:'Content', domain:'Domain', category:'Category', recordType:'Record type', language:'Language', motion:'Reduce motion', sort:'Sort', newest:'Recently recorded', eventNewest:'Subject date — newest', eventOldest:'Subject date — oldest', titleSort:'Title', insufficient:'Your clearance does not include the full text of this record.', emptyRecent:'No recent records.', emptyBookmarks:'No bookmarks on file.', setup:'Archive connection required', setupBody:'Connect a Supabase project to synchronize accounts, shared records, and bookmarks across devices.', setupAction:'View setup guide', menu:'Open menu', close:'Close', allKnowledge:'All knowledge', connected:'Connected knowledge', perspective:'Many perspectives', evidence:'Verifiable sources', why:'What is the Akashic Records?', whyBody:'The name comes from an old idea that events and thoughts leave enduring traces. This site does not present that belief as supernatural fact. It reimagines the idea as a shared archive where anyone can preserve verifiable knowledge and lived experience, connected by sources, time, and relationships.'
  },
  ja: {
    skip:'本文へ移動', archive:'アカシック・レコード', tagline:'人と世界の知識をつなぎ、保存する生きた記録庫', warning:'知識は所有物ではなく、受け継がれる記憶です。', warningBody:'歴史、科学、芸術、人物、場所、思想、個人の経験を相互につなぎます。根拠を示し、多様な視点を尊重し、未来の読者のために記録してください。', login:'ログイン', signup:'記録者登録', logout:'ログアウト', email:'メール', password:'パスワード', confirm:'パスワード確認', displayName:'表示名', consent:'利用規約とプライバシーポリシーに同意します', submit:'続ける', cancel:'キャンセル', reset:'パスワード再設定', resetSent:'アカウントの有無に関係なく案内メールが送信されます。', authFailed:'認証に失敗しました。入力内容をご確認ください。', verify:'メールの認証リンクをご確認ください。', explore:'探索', home:'すべての記録', topics:'知識領域', collections:'コレクション', bookmarks:'ブックマーク', mine:'自分の記録', newRecord:'新規記録', settings:'設定', about:'紹介', search:'記録を検索', searchHint:'タイトル、要約、タグから検索', breadcrumb:'現在地', totalRecords:'公開記録', todayRecords:'本日の記録', contributors:'記録者', recent:'最近の閲覧', noRecords:'まだ保存された記録がありません。', retry:'再試行', loadMore:'さらに読み込む', details:'記録を開く', source:'出典', eventDate:'対象時点', createdAt:'記録日', author:'記録者', level:'閲覧レベル', tags:'タグ', edit:'編集', delete:'削除', report:'報告', save:'保存', title:'タイトル', summary:'要約', content:'本文', domain:'知識領域', category:'分類', recordType:'記録形式', language:'言語', motion:'動きを減らす', sort:'並び順', newest:'記録日の新しい順', eventNewest:'対象時点の新しい順', eventOldest:'対象時点の古い順', titleSort:'タイトル順', insufficient:'この記録の全文を閲覧する権限がありません。', emptyRecent:'最近閲覧した記録はありません。', emptyBookmarks:'保存した記録はありません。', setup:'アーカイブへの接続が必要です', setupBody:'Supabaseを接続すると、アカウント、共有記録、ブックマークが端末間で同期されます。', setupAction:'設定方法を見る', menu:'メニューを開く', close:'閉じる', allKnowledge:'すべての知識', connected:'つながる知識', perspective:'多様な視点', evidence:'検証可能な出典', why:'アカシック・レコードとは？', whyBody:'名称は、世界の出来事や思考が痕跡として保存されるという古い概念に由来します。本サイトはそれを超自然的事実として主張しません。検証可能な知識と個人の経験を、出典・時間・関係で結ぶ共同知識庫として再解釈しています。'
  }
};

Object.assign(window.I18N.ko,{moderation:'검토 회의',underReview:'검토 회의 진행 중',reportReason:'신고 사유',reportDetail:'상세 설명',reportSent:'신고가 접수되었습니다. 신고 3건이 모이면 기록을 삭제하지 않고 관리자 검토 회의를 엽니다.',reviewIntro:'세 명의 독립된 관리자가 출처와 신고 내용을 검토하고 투표합니다. 세 표가 모이기 전까지 기록은 공개 상태로 유지됩니다.',keep:'기록 유지',hide:'기록 숨김',voteNote:'판단 근거',votes:'관리자 의견',reports:'접수된 신고',meetingOpen:'회의 진행 중',meetingResolved:'회의 종료',falseInformation:'허위 정보',missingSource:'출처 없음',fiction:'창작물',inappropriate:'부적절한 내용',other:'기타',cannotVoteOwn:'자신이 작성한 기록의 검토에는 참여할 수 없습니다.'});
Object.assign(window.I18N.en,{moderation:'Review council',underReview:'Review meeting in progress',reportReason:'Report reason',reportDetail:'Details',reportSent:'Report received. Three reports open a moderator review instead of deleting the record.',reviewIntro:'Three independent administrators review the sources and reports. The record remains public until three votes have been cast.',keep:'Keep record',hide:'Hide record',voteNote:'Reasoning',votes:'Moderator opinions',reports:'Submitted reports',meetingOpen:'Meeting open',meetingResolved:'Meeting resolved',falseInformation:'False information',missingSource:'Missing source',fiction:'Fiction presented as fact',inappropriate:'Inappropriate content',other:'Other',cannotVoteOwn:'You cannot vote on your own record.'});
Object.assign(window.I18N.ja,{moderation:'審査会議',underReview:'審査会議中',reportReason:'報告理由',reportDetail:'詳細',reportSent:'報告を受け付けました。3件集まると記録を削除せず、管理者の審査会議を開始します。',reviewIntro:'3人の独立した管理者が出典と報告を確認し投票します。3票が集まるまで記録は公開されます。',keep:'記録を維持',hide:'記録を非表示',voteNote:'判断理由',votes:'管理者の意見',reports:'受理した報告',meetingOpen:'会議中',meetingResolved:'会議終了',falseInformation:'虚偽情報',missingSource:'出典なし',fiction:'創作物',inappropriate:'不適切な内容',other:'その他',cannotVoteOwn:'自分の記録には投票できません。'});
Object.assign(window.I18N.ko,{related:'관련 기록',confirmDelete:'이 기록을 삭제하시겠습니까? 삭제 후 직접 복원할 수 없습니다.',deleted:'기록이 삭제되었습니다.',translationHelp:'한국어는 필수이며 영어와 일본어는 선택입니다.'});
Object.assign(window.I18N.en,{related:'Related records',confirmDelete:'Delete this record? You cannot restore it yourself.',deleted:'Record deleted.',translationHelp:'Korean is required; English and Japanese are optional.'});
Object.assign(window.I18N.ja,{related:'関連記録',confirmDelete:'この記録を削除しますか？自分で復元することはできません。',deleted:'記録を削除しました。',translationHelp:'韓国語は必須、英語と日本語は任意です。'});
Object.assign(window.I18N.ko,{levelHigh:'보안등급 높은순'});Object.assign(window.I18N.en,{levelHigh:'Highest clearance'});Object.assign(window.I18N.ja,{levelHigh:'閲覧レベルの高い順'});
